### ISSUE TITLE
Foster dog faq

### ISSUE THREAD

**Issue by definitelyDaphne** [codersforcauses/bfa-rescue#34]
recreate the faq section that they currently have 
![Screen Shot 2021-01-09 at 5 05 53 pm](https://user-images.githubusercontent.com/49707328/104087751-f09b0880-529c-11eb-99ca-31eb6ddfd02d.png)

need to check with client see if they'd like to modify the question/answer

store the question and answer in json and pull it in for display

**Comment by definitelyDaphne** [comment]
close #34

**Comment by Drewbi** [comment]
Definitely use these when tackling this page: https://vuetifyjs.com/en/components/expansion-panels/#expansion-panels

**Comment by bpgoodwin** [comment]
Completed this and has been used under the Volunteer and Foster pages.
